name: Publish
on:
  workflow_call:
    secrets:
      CURSEFORGE_TOKEN:
        description: CurseForge Token
        required: false
      MODRINTH_TOKEN:
        description: Modrinth Token
        required: false
      PUBLISH_USER:
        description: Nexus Username
        required: false
      PUBLISH_PASSWORD:
        description: Nexus Password
        required: false

jobs:
  build:
    runs-on: self-hosted
    env:
      cf_key: ${{ secrets.CURSEFORGE_TOKEN }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
      nexus_uname: ${{ secrets.PUBLISH_USER }}
      nexus_pwd: ${{ secrets.PUBLISH_PASSWORD }}
      ref_name: ${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Gradle
      run: chmod +x ./gradlew && ./gradlew build
    - name: Publish to Nexus
      if: env.nexus_uname != null && env.nexus_pwd != null
      run: ./gradlew publish
    - name: Publish to Modrinth
      if: env.modrinth_token != null
      run: ./gradlew modrinth
    - name: Publish to CurseForge
      if: env.cf_key != null
      run: ./gradlew curseforge
